### ISSUE TITLE
MCAD\regular_shapes.scad -  test line error

### ISSUE THREAD

**Issue by MichaelAtOz** [diara628/MCAD#19]
The last line:
test_square_pyramid(){square_pyramid(10, 20, 30);}
Needs `module` prefixed or commented out/deleted.
Causes a warning when `include <>`ed

**Comment by sk8nfool** [comment]
So how long before this is fixed? Still a problem in openscad-nightly (not sure which version - maybe 2020.01.25 but might be 2020-04-08)

**Comment by diara628** [comment]
Fixed
